In [ ]:
!pip install numpy

  Using cached numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Using cached numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)


In [ ]:
! pip install opencv-python   

  Using cached opencv_python-5.0.0.93-cp37-abi3-macosx_13_0_arm64.whl.metadata (19 kB)
Using cached opencv_python-5.0.0.93-cp37-abi3-macosx_13_0_arm64.whl (48.3 MB)


In [ ]:
import cv2 as cv2
import numpy as np
pixel = np.array(cv2.imread("image.jpg" , 0));
pixel = pixel.astype('uint8')
sz = pixel.shape;

print(pixel[0]);
c = 255/np.log(1+255);
for i in range(0,sz[0]) :
    for j in range(0 , sz[1]):
            val = pixel[i][j];
            s = c*(np.log(1 + val));
            pixel[i,j] = np.uint8(s)
print(pixel);
cv2.imshow("converted" ,pixel)
cv2.waitKey(0)
cv2.destroyAllWindows()

[163 156 172 ... 180 170 163]


/var/folders/jn/fwppxh7n15nbw6nvkcky_vhc0000gn/T/ipykernel_8384/548412011.py:12: RuntimeWarning: overflow encountered in scalar add
  s = c*(np.log(1 + val));
/var/folders/jn/fwppxh7n15nbw6nvkcky_vhc0000gn/T/ipykernel_8384/548412011.py:12: RuntimeWarning: divide by zero encountered in log
  s = c*(np.log(1 + val));
/var/folders/jn/fwppxh7n15nbw6nvkcky_vhc0000gn/T/ipykernel_8384/548412011.py:13: RuntimeWarning: invalid value encountered in cast
  pixel[i,j] = np.uint8(s)


[[234 232 236 ... 239 236 234]
 [236 238 236 ... 234 236 242]
 [236 235 230 ... 241 241 236]
 ...
 [239 239 244 ... 244 247 249]
 [244 238 241 ... 245 249 249]
 [243 246 244 ... 246 245 247]]
